### ISSUE TITLE
Copyright and licensing for REUSE.toml?

### ISSUE THREAD

**Issue by MarkCallow** [fsfe/reuse-tool#1040]
After using `reuse convert-dep5` I ended up down a rat-hole trying to provide copyright and licensing information for `REUSE.toml`.  I found the whole experience very user unfriendly.

```bash
$ reuse convert-dep5
$ reuse lint
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* REUSE.toml
```

I searched for how to include comments in a .toml file. Then I read the REUSE.toml section of the REUSE specification v3.2 which says nothing about this info being required or how to provide it. So I tried the following. None of them worked. 

```toml
version = 1
SPDX-PackageName = "KTX-Software"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/KTX-Software"
SPDX-FileCopyrightText = "2024 The Khronos Group Inc."
SPDX-License-Identifier = "Apache-2.0"
```

```toml
version = 1
SPDX-FileCopyrightText = "2024 The Khronos Group Inc."
SPDX-License-Identifier = "Apache-2.0"
SPDX-PackageName = "KTX-Software"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/KTX-Software"
```

```toml
version = 1
SPDX-PackageName = "KTX-Software"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/KTX-Software"
# SPDX-FileCopyrightText = "2024 The Khronos Group Inc."
# SPDX-License-Identifier = "Apache-2.0"
```

Then I tried

```toml
version = 1
SPDX-PackageName = "KTX-Software"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/KTX-Software"

[[annotations]]
SPDX-FileCopyrightText = "2024 The Khronos Group Inc."
SPDX-License-Identifier = "Apache-2.0"
```

which produced

```
usage: reuse [-h] [--debug] [--suppress-deprecation] [--include-submodules]
             [--include-meson-subprojects] [--no-multiprocessing]
             [--root PATH] [--version]
             {annotate,download,lint,spdx,supported-licenses,supported-licences,convert-dep5}
             ...
reuse: error: '.' could not be parsed. We received the following error message: 'path' must not be empty.
```

Note the conspicuous absence of a line number where the parsing error was. In this case since I had just added the annotation, I knew were the error had to be. Nevertheless, in my view, failing to provide line numbers or context in such errors is a sackable offence. 

Finally I tried
```toml
version = 1
SPDX-PackageName = "KTX-Software"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/KTX-Software"

[[annotations]]
path = "REUSE.toml"
SPDX-FileCopyrightText = "2024 The Khronos Group Inc."
SPDX-License-Identifier = "Apache-2.0"
```
The first way I tried seemed the most logical to me. The way that I eventually found worked seems circular to me. 

Why require copyright and licensing info for `REUSE.toml`? It wasn't required for  `dep5`. If it must be provided, `convert-dep5` should print a message about it with information about how to add it.  Even better it could prompt for the copyright string and license name and add it to the file itself.

**Comment by carmenbianca** [comment]
Hi @MarkCallow ! We discussed this same problem internally last Friday. We're in agreement that we should change this.

Regarding how to solve this for now:

```toml
# SPDX-FileCopyrightText: 2024 Jane Doe
# 
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
key = "value"
```
