### ISSUE TITLE
Certain glob patterns matching folders in the README.toml do not work

### ISSUE THREAD

**Issue by brlin-tw** [fsfe/reuse-tool#1071]
The following project filetree:

```txt
.
├── folder-1
│   └── README.md
├── LICENSES
│   └── WTFPL.txt
├── README.md
└── REUSE.toml
```

with the following REUSE.toml rules:

```toml
version = 1

[[annotations]]
path = [
    "README.md"
]
SPDX-FileCopyrightText = '2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'WTFPL'

[[annotations]]
path = [
    "folder-*/README.md"
]
SPDX-FileCopyrightText = '2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'WTFPL'
```

resulted in the following REUSE tool lint error:

```txt
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* folder-1/README.md
```

Refer to <https://gitlab.com/brlin/reuse-tool-not-able-to-match-folder-glob-problem> for the problem reproducer.

## Known workaround

Replace the single asterisk in the filename pattern to double asterisks works, somehow:

```toml
[[annotations]]
path = [
    "folder-**/README.md"
]
```
