### ISSUE TITLE
performance issue in pre-commit-hook

### ISSUE THREAD

**Issue by spaceone** [fsfe/reuse-tool#1177]
Running the reuse-lint-file pre-commit hook for all 55345 files in our [repository](https://github.com/univention/univention-corporate-server/) takes more than 3 minutes.
 ```
$ time pre-commit run reuse-lint-file -a
…
real    3m26,169s
user    19m37,665s
sys     2m57,382s
```

→ That's way too long.

The pre-commit-config:
```
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file
```
