### ISSUE TITLE
provide a pre-commit hook to add missing license information

### ISSUE THREAD

**Issue by spaceone** [fsfe/reuse-tool#1178]
It would be nice to have a pre-commit hook, which adds missing license information, where just the default license is taken either from a pre-commit argument (don't know how this would work) or from the `REUSE.toml`.

```
- id: reuse-lint-file
  name: reuse lint-file
  entry: reuse
  args: ["annotate", "-c", GET_DEFAULT_FROM_TOML, "-l", GET_DEFAULT_FROM_TOML, "--skip-unrecognised", "--skip-existing"]
  language: python
  description:
    "Make the changed files compliant with the REUSE Specification."
```
