### ISSUE TITLE
Add plugin support for unsupported comment styles

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#177]
There's a decent likelihood that some obscure comment style is not supported, or that a file extension is not recognised by the tool. This is annoying, because adding support for these things requires a new release of the tool. And while new comment styles and extensions *should* be supported in new releases, the interim should also offer a solution.

Paired with the almost-forgotten #68, I suspect this could be possible. Simply allow the user to define stuff in a configuration file:

```yaml
styles:
  custom_c:
    multi_line: ["/*", "*", "*/"]
    indent_before_middle: " "
    indent_after_middle: " "
    indent_before_end: " "
    extensions: [".c", ".cpp"]
  custom_py:
    single_line: "#"
    indent_after_single: " "
    extensions: [".py"]
```

Something like that. The downside is that this will not allow support for complex comment styles. You'd need code for those.
