### ISSUE TITLE
Gitlab CI instructions no longer work

### ISSUE THREAD

**Issue by mikix** [fsfe/reuse-tool#223]
I have a project in a Gitlab instance, which used the fsfe/reuse docker image to run a CI check.

It's configuration is as documented here: https://reuse.software/dev/
```
reuse:
  image: fsfe/reuse:latest
  script:
    - reuse lint
```

I noticed that recently, it's failing with `reuse: error: invalid choice: 'sh' (choose from 'addheader', 'download', 'init', 'lint', 'spdx')`

I assume that's because Gitlab is trying to run `sh "reuse lint"` in the docker image, but that image now always passes commands directly to the reuse script.

**Comment by carmenbianca** [comment]
Huh, that *is* weird. I would have imagined that GitLab CI overrode the entrypoint.

Two solutions, then:

First solution adapted from [here](https://forum.gitlab.com/t/how-to-override-entrypoint-in-gitlab-ci-yml/9429):

```yaml
reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
```

Or second solution:

```yaml
reuse:
  image: fsfe/reuse:latest
  script:
    - lint
```
