### ISSUE TITLE
Provide a standard pre-commit hook

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-tool#538]
Recently I discovered [pre-commit](https://pre-commit.com/) as a framework to easily setup checks for a codebase which can be called as a git commit hook or standalone. The value is in reusability and ease of use.

REUSE could provide a pre-commit hook so others can easily integrate REUSE in their projects.

**Comment by nicorikken** [comment]
I have a minimal working example in a `.pre-commit-config.yaml` using the `local` repo to define it inline:
```yaml
repos:
- repo: local
  hooks:
  - id: reuse
    name: REUSE lint
    entry: "reuse lint"
    language: python
    pass_filenames: false
```
This results in the following output when it succeeds:
```shell
$ git commit --signoff
REUSE lint...............................................................Passed
```
And it shows the details if it fails:
```shell
$ git commit -signoff
REUSE lint...............................................................Failed
- hook id: reuse
- exit code: 1

# MISSING LICENSES

'MIT' found in:
* .pre-commit-config.yaml


# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses: MIT
* Unused licenses:
* Used licenses: Apache-2.0, CC-BY-SA-4.0, GPL-2.0-or-later, MIT
* Read errors: 0
* Files with copyright information: 9 / 9
* Files with license information: 9 / 9

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

It would be nice to contribute this pre-commit hook somewhere to make it even easier to apply it. And there could be variants like a commit hook to call `addheader` on changed files and run `download --all`.

**Comment by carmenbianca** [comment]
Should we not provide a hook, and document a config?

e.g. [black's hook](https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml)

**Comment by nicorikken** [comment]
LOL, in trying to create this hook for REUSE it turned out it was already present in the repository: I'll add it to the general index.
I already tried it for my repo and it works:
```yaml
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
      - id: reuse
```
And then documentation is left.
