### ISSUE TITLE
Test reuse against itself on Windows/macOS

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-tool#798]
this check:

```
  reuse:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-interaction --no-dev
      - name: Test REUSE compliance
        run: |
          make reuse
```

let's also do that using windows and macOS
