### ISSUE TITLE
Dep5 Duplicate field "Copyright": Fails to parse many files with REUSE v2.1.0 Release

### ISSUE THREAD

**Issue by cordlandwehr** [fsfe/reuse-tool#803]
Hi, in the KDE repos, our CI just picked up the new REUSE release and apparently this introduces a severe regression. Eg. in this job we suddenly have all files not being able to be read: https://invent.kde.org/system/partitionmanager/-/jobs/1064900
Any ideas what might going wrong here?

**Comment by mxmehl** [comment]
I cannot reproduce this using my employer's GitLab instance in which also fsfe/reuse:latest is used. I made sure it's using the latest REUSE version.

This is the slightly redacted `.gitlab-ci.yml`:

```yaml
---
reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint --json
```
