### ISSUE TITLE
wrong parsing of files containing quote-wrapped SPDX headers to be added other files

### ISSUE THREAD

**Issue by alpianon** [fsfe/reuse-tool#891]
when parsing files containing code that adds SPDX headers to other files or generates source code files with SPDX headers, like this one (https://github.com/qt/qtbase/blob/dev/util/gradientgen/gradientgen.cpp):

```cpp
// Copyright (C) 2018 The Qt Company Ltd.
// Copyright (C) 2019 Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author Giuseppe D'Angelo <giuseppe.dangelo@kdab.com>
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0

#include <iostream>

[...]

#include <QColor>

using namespace std;

static const char LICENSE_HEADER[] =
R"(
// Copyright (C) 2019 Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author Giuseppe D'Angelo <giuseppe.dangelo@kdab.com>
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
)";

class Printer {
    Q_DISABLE_COPY_MOVE(Printer)
public:
```

REUSE tool thinks that the text between quotes is an additional SPDX header, creating an SPDX file entry like this:

```yaml
FileName: ./util/gradientgen/gradientgen.cpp
SPDXID: SPDXRef-c0dbe8edc6627db5d6ec86eb0f8e3aca
FileChecksum: SHA1: 4e795d740504f2cd98c17ebae11a8084e5b13e2f
LicenseConcluded: (GPL-2.0-only OR GPL-3.0-only OR LGPL-3.0-only OR LicenseRef-Qt-Commercial) AND (GPL-3.0-only WITH Qt-GPL-exception-1.0 OR LicenseRef-Qt-Commercial)
LicenseInfoInFile: GPL-2.0-only
LicenseInfoInFile: GPL-3.0-only
LicenseInfoInFile: GPL-3.0-only
LicenseInfoInFile: LGPL-3.0-only
LicenseInfoInFile: LicenseRef-Qt-Commercial
LicenseInfoInFile: LicenseRef-Qt-Commercial
LicenseInfoInFile: Qt-GPL-exception-1.0
FileCopyrightText: <text>Copyright (C) 2018 The Qt Company Ltd.
Copyright (C) 2019 Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author Giuseppe D'Angelo <giuseppe.dangelo@kdab.com></text>
```

Both the LicenseConcluded and (half of) the LicenseInfoInFile fields are wrong.
The expected behavior is that REUSE tool ignores SPDX tags wrapped in quotes, to avoid such kind of false positives

Steps to reproduce:

- install REUSE tool
- download https://download.qt.io/archive/qt/6.5/6.5.3/submodules/qtbase-everywhere-src-6.5.3.tar.xz and extract it
- within the dir where you extracted source directory, do:

```bash
cd qtbase-everywhere-src-6.5.3/
reuse spdx --add-license-concluded --creator-person "John Doe" --creator-organization ACME \ 
  > ../qtbase-everywhere-src-6.5.3.spdx.tag
```
